### ISSUE TITLE
PIN test for DebitCardTest

### ISSUE THREAD

**Issue by JustinPraas** [cjcr-andrei/ING-UT#16]
I've been struggling a little with the DebitCardTest. To test whether an entered PIN is correct, we use the isValidPIN method. However, we do not know the actual PIN of the DebitCard, as it is generated on instantiation, nor do we have a get/set method (for obvious security reasons).

Even though the isValidPIN method is a very simple method, I do think that we should test it. Do you see a solution?

**Comment by cjcr-andrei** [comment]
We would probably need a getter one way or another. As Arend said, security is outside of the scope of this project and we should not concern ourselves with it unless otherwise specified in an extension.

**Comment by cjcr-andrei** [comment]
Fixed. Method is now in unit tests.
