### ISSUE TITLE
SQL bug: Apostrophe (') sign causes SQL error and debit/credit method doesn't actually add/subtract from balance

### ISSUE THREAD

**Issue by JustinPraas** [cjcr-andrei/ING-UT#18]
1. Small bug where apostrophes in credit/debit descriptions cause an SQL error (which also means that the credit/debit is not completed, **even though in the current TUI implementation it says it does.**
2. Debit/credit methods in BankAccount do _log_ the payments, but not actually add/subtract them from the bank account balance.

**Comment by cjcr-andrei** [comment]
1. Shouldn't be a problem anymore, now that we use Hibernate. 

2. Debit/credit methods no longer make the payment persistent, you need to call saveToDB() in your code after you use them. This is to ensure that we don't execute partial transactions.
